update_tests = function(target, deps, gen_func) {

  stopifnot(all(file.exists(c(target,deps))))

  outdated = purrr::map2_dbl(
    target, deps, ~ diff(file.info(c(.x, .y))$mtime)
  )

  if (any(outdated > 0)) {
    message("Generating ", target)
    flat = purrr::reduce(
      gen_func(),
      ~ c(.x, "", .y),
      .init = c("# Generated by helper-tests.R, do not edit by hand")
    )
    writeLines(
      styler::style_text(flat),
      target
    )
  }
}

if (Sys.getenv("CI") == "" && file.exists("../../R/tests.R")) {
  # Only run if tests.R is younger than the output

  gfm_deps = c("helper-tests.R", "../../R/tests.R", "../../inst/specs/gfm/spec.txt")
  update_tests("test-to_html-gfm.R", gfm_deps, gfm_tests_to_html)
  update_tests("test-to_md-gfm.R", gfm_deps, gfm_tests_to_md)

  md4c_deps = c("helper-tests.R", "../../R/tests.R", dir("../../inst/specs/md4c/", pattern = "*.txt", full.names = TRUE))
  update_tests("test-to_html-md4c.R", gfm_deps, md4c_tests_to_html)
  update_tests("test-to_md-md4c.R", gfm_deps, md4c_tests_to_md)
}
