# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_md_cpp <- function(x, flag) {
    .Call(`_md4r_parse_md_cpp`, x, flag)
}

flag_mask <- function(flags) {
    .Call(`_md4r_flag_mask`, flags)
}

