# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

encodeURI <- function(value) {
    .Call(`_md4r_encodeURI`, value)
}

encodeURIComponent <- function(value) {
    .Call(`_md4r_encodeURIComponent`, value)
}

decodeURI <- function(value) {
    .Call(`_md4r_decodeURI`, value)
}

decodeURIComponent <- function(value) {
    .Call(`_md4r_decodeURIComponent`, value)
}

parse_md_cpp <- function(x, flag) {
    .Call(`_md4r_parse_md_cpp`, x, flag)
}

flag_mask <- function(flags) {
    .Call(`_md4r_flag_mask`, flags)
}

flag_is_set <- function(flags, check) {
    .Call(`_md4r_flag_is_set`, flags, check)
}

table_entry_escape <- function(x) {
    .Call(`_md4r_table_entry_escape`, x)
}

